package com.example.linkkeeper.ui.theme
import androidx.compose.ui.graphics.Color

// Custom colors - Light theme
val primaryCustomLight = Color(0xFF2563EB)
val primaryDarkCustomLight = Color(0xFF1E40AF)
val primaryDarkerCustomLight = Color(0xFF172554)
val primaryLightCustomLight = Color(0xFF60A5FA)
val primaryDisabledCustomLight = Color(0xFF93C5FD)
val backgroundCustomLight = Color(0xFFF8FAFC)
val surfaceCustomLight = Color(0xFFFFFFFF)
val borderCustomLight = Color(0xFFE5E7EB)
val successCustomLight = Color(0xFF22C55E)
val successLightCustomLight = Color(0xFFBBF7D0)
val warningCustomLight = Color(0xFFFACC15)
val warningLightCustomLight = Color(0xFFFEF9C3)
val errorCustomLight = Color(0xFFEF4444)
val errorLightCustomLight = Color(0xFFFECACA)
val textCustomLight = Color(0xFF111827)
val subtextCustomLight = Color(0xFF6B7280)
val textLinkCustomLight = Color(0xFF2563EB)
val textPlaceholderCustomLight = Color(0xFFCBD5E1)
val textErrorCustomLight = Color(0xFFEF4444)
val textSuccessCustomLight = Color(0xFF22C55E)
val textWarningCustomLight = Color(0xFFFACC15)
val textDisabledCustomLight = Color(0xFF93C5FD)

// Custom colors - Dark theme
val primaryCustomDark = Color(0xFF2563EB)
val primaryDarkCustomDark = Color(0xFF60A5FA)
val primaryDarkerCustomDark = Color(0xFF93C5FD)
val primaryLightCustomDark = Color(0xFF1E40AF)
val primaryDisabledCustomDark = Color(0xFF172554)
val backgroundCustomDark = Color(0xFF1E293B)
val surfaceCustomDark = Color(0xFF334155)
val borderCustomDark = Color(0xFF475569)
val successCustomDark = Color(0xFF4ADE80)
val successLightCustomDark = Color(0xFF166534)
val warningCustomDark = Color(0xFFFDE047)
val warningLightCustomDark = Color(0xFF92400E)
val errorCustomDark = Color(0xFFF87171)
val errorLightCustomDark = Color(0xFF991B1B)
val textCustomDark = Color(0xFFF8FAFC)
val subtextCustomDark = Color(0xFFCBD5E1)
val textLinkCustomDark = Color(0xFF60A5FA)
val textPlaceholderCustomDark = Color(0xFF6B7280)
val textErrorCustomDark = Color(0xFFF87171)
val textSuccessCustomDark = Color(0xFF4ADE80)
val textWarningCustomDark = Color(0xFFFDE047)
val textDisabledCustomDark = Color(0xFF334155)
